import { query } from '../config/db.js';
export async function getProducts(req,res){try{const search=req.query.search||'';const rows=await query(`SELECT p.*, c.name category_name, s.name supplier_name,
CASE WHEN p.stock_quantity=0 THEN 'Out of Stock' WHEN p.stock_quantity<=p.minimum_stock THEN 'Low Stock' ELSE 'In Stock' END stock_status
FROM products p LEFT JOIN categories c ON c.id=p.category_id LEFT JOIN suppliers s ON s.id=p.supplier_id
WHERE p.name LIKE ? OR p.sku LIKE ? ORDER BY p.created_at DESC`,[`%${search}%`,`%${search}%`]);res.json(rows);}catch(e){res.status(500).json({message:e.message});}}
export async function getProduct(req,res){try{const rows=await query('SELECT * FROM products WHERE id=?',[req.params.id]);res.json(rows[0]);}catch(e){res.status(500).json({message:e.message});}}
export async function createProduct(req,res){try{const {name,sku,category_id,supplier_id,buying_price,selling_price,stock_quantity,minimum_stock,image,description,status}=req.body;if(!name||!sku)return res.status(400).json({message:'Product name and SKU are required.'});const r=await query('INSERT INTO products (name,sku,category_id,supplier_id,buying_price,selling_price,stock_quantity,minimum_stock,image,description,status) VALUES (?,?,?,?,?,?,?,?,?,?,?)',[name,sku,category_id||null,supplier_id||null,buying_price||0,selling_price||0,stock_quantity||0,minimum_stock||5,image||'',description||'',status||'active']);res.status(201).json({id:r.insertId,...req.body});}catch(e){res.status(500).json({message:e.message});}}
export async function updateProduct(req,res){try{const {name,sku,category_id,supplier_id,buying_price,selling_price,stock_quantity,minimum_stock,image,description,status}=req.body;await query('UPDATE products SET name=?, sku=?, category_id=?, supplier_id=?, buying_price=?, selling_price=?, stock_quantity=?, minimum_stock=?, image=?, description=?, status=? WHERE id=?',[name,sku,category_id||null,supplier_id||null,buying_price||0,selling_price||0,stock_quantity||0,minimum_stock||5,image||'',description||'',status||'active',req.params.id]);res.json({message:'Product updated.'});}catch(e){res.status(500).json({message:e.message});}}
export async function deleteProduct(req,res){try{await query('DELETE FROM products WHERE id=?',[req.params.id]);res.json({message:'Product deleted.'});}catch(e){res.status(500).json({message:e.message});}}
