import express from 'express';
import { login, register, profile, listUsers } from '../controllers/authController.js';
import { protect } from '../middleware/authMiddleware.js';
import { allowRoles } from '../middleware/roleMiddleware.js';
const router=express.Router();
router.post('/login',login);
router.post('/register',protect,allowRoles('admin'),register);
router.get('/profile',protect,profile);
router.get('/users',protect,allowRoles('admin'),listUsers);
export default router;
