import express from 'express';
import cors from 'cors';
import morgan from 'morgan';
import dotenv from 'dotenv';
import authRoutes from './routes/authRoutes.js';
import productRoutes from './routes/productRoutes.js';
import categoryRoutes from './routes/categoryRoutes.js';
import supplierRoutes from './routes/supplierRoutes.js';
import purchaseRoutes from './routes/purchaseRoutes.js';
import saleRoutes from './routes/saleRoutes.js';
import stockAdjustmentRoutes from './routes/stockAdjustmentRoutes.js';
import reportRoutes from './routes/reportRoutes.js';

dotenv.config();
const app=express();
app.use(cors({origin:process.env.FRONTEND_URL||'http://localhost:5173',credentials:true}));
app.use(express.json());
app.use(morgan('dev'));
app.get('/',(req,res)=>res.json({message:'StockFlow Inventory API is running'}));
app.use('/api/auth',authRoutes);
app.use('/api/products',productRoutes);
app.use('/api/categories',categoryRoutes);
app.use('/api/suppliers',supplierRoutes);
app.use('/api/purchases',purchaseRoutes);
app.use('/api/sales',saleRoutes);
app.use('/api/stock-adjustments',stockAdjustmentRoutes);
app.use('/api/reports',reportRoutes);
app.use((err,req,res,next)=>res.status(500).json({message:err.message||'Server error'}));
const PORT=process.env.PORT||5000;
app.listen(PORT,()=>console.log(`StockFlow API running on port ${PORT}`));
